version: '3'

services:
  restic-pg-dump:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      # BACKUP_SCHEDULE: '0 * * * *'  # Hourly
      # PRUNE_SCHEDULE: '0 14 * * 0'  # Sunday midnight, AEST. Use '' to disable.
      DBHOST:
      DBPASSWORD:
      # DBPORT: 3306
      DBUSER:
      # RESTIC_KEEP_HOURLY: 24
      # RESTIC_KEEP_DAILY: 7
      # RESTIC_KEEP_WEEKLY: 4
      # RESTIC_KEEP_MONTHLY: 12
      RESTIC_PASSWORD:
      RESTIC_REPOSITORY:
    image: techknowlogick/restic-mysqldump
    restart: unless-stopped
